CREATE TABLE JOBS 
   (	JOB_ID VARCHAR2(10), 
	JOB_TITLE VARCHAR2(35), 
	MIN_SALARY NUMBER(6,0), 
	MAX_SALARY NUMBER(6,0)
   );
  
INSERT INTO JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) 
	 SELECT 'AD_PRES','President',20080,40000 FROM DUAL UNION ALL
	 SELECT 'AD_VP','Administration Vice President',15000,30000 FROM DUAL UNION ALL
	 SELECT 'AD_ASST','Administration Assistant',3000,6000 FROM DUAL UNION ALL
	 SELECT 'FI_MGR','Finance Manager',8200,16000 FROM DUAL UNION ALL
	 SELECT 'FI_ACCOUNT','Accountant',4200,9000 FROM DUAL UNION ALL
	 SELECT 'AC_MGR','Accounting Manager',8200,16000 FROM DUAL UNION ALL
	 SELECT 'AC_ACCOUNT','Public Accountant',4200,9000 FROM DUAL UNION ALL
	 SELECT 'SA_MAN','Sales Manager',10000,20080 FROM DUAL UNION ALL
	 SELECT 'SA_REP','Sales Representative',6000,12008 FROM DUAL UNION ALL
	 SELECT 'PU_MAN','Purchasing Manager',8000,15000 FROM DUAL UNION ALL
	 SELECT 'PU_CLERK','Purchasing Clerk',2500,5500 FROM DUAL UNION ALL
	 SELECT 'ST_MAN','Stock Manager',5500,8500 FROM DUAL UNION ALL
	 SELECT 'ST_CLERK','Stock Clerk',2008,5000 FROM DUAL UNION ALL
	 SELECT 'SH_CLERK','Shipping Clerk',2500,5500 FROM DUAL UNION ALL
	 SELECT 'IT_PROG','Programmer',4000,10000 FROM DUAL UNION ALL
	 SELECT 'MK_MAN','Marketing Manager',9000,15000 FROM DUAL UNION ALL
	 SELECT 'MK_REP','Marketing Representative',4000,9000 FROM DUAL UNION ALL
	 SELECT 'HR_REP','Human Resources Representative',4000,9000 FROM DUAL UNION ALL
	 SELECT 'PR_REP','Public Relations Representative',4500,10500 FROM DUAL;
   

--selectJobAll
	SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY 
	 FROM JOBS;

--selectJobOne
	SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY 
	 FROM JOBS j
	 WHERE JOB_ID='AD_PRES';
	
--deleteJob
	DELETE FROM JOBS j
	 WHERE JOB_ID='IT_PROG';
	
--updateJob
	UPDATE JOBS SET JOB_TITLE='PROGRAMMER'
	 WHERE JOB_ID='IT_PROG';
	
--insertJob
	INSERT INTO JOBS j (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY )
	 VALUES('IT_PROG','DEVELOPER','1000','10000');
	
